export const testSetLists = [
    {
        name: 'My First Set List',
        songs: ['Song A', 'Song B', 'Song C'],
    },
    {
        name: 'Chill Vibes',
        songs: ['Song D', 'Song E', 'Song F'],
    },
]

export const testSongs = [
    {
        id: 'Song A',
        title: 'Song A',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song B',
        title: 'Song B',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song C',
        title: 'Song C',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {  
        id: 'Song D',
        title: 'Song D',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song E',
        title: 'Song E',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    }, 
    {
        id: 'Song F',
        title: 'Song F',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    }
]