import { Timestamp } from "firebase/firestore"

export const testSetLists = [
    {
        name: 'My First Set List',
        createdAt: Timestamp.now(),
        createdBy: 'user1',
        bandId: 'band1',
        id: 'setlist1',
    },
]

export const keys: string[] = [
    'C Major', 'C Minor',
    'C# Major', 'C# Minor',
    'D Major', 'D Minor',
    'Eb Major', 'Eb Minor',
    'E Major', 'E Minor',
    'F Major', 'F Minor',
    'F# Major', 'F# Minor',
    'G Major', 'G Minor',
    'Ab Major', 'Ab Minor',
    'A Major', 'A Minor',
    'Bb Major', 'Bb Minor',
    'B Major', 'B Minor'
]

export const testSongs = [
    {
        id: 'Song A',
        title: 'Song A',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song B',
        title: 'Song B',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song C',
        title: 'Song C',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {  
        id: 'Song D',
        title: 'Song D',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    },
    {
        id: 'Song E',
        title: 'Song E',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    }, 
    {
        id: 'Song F',
        title: 'Song F',
        artist: 'Test',
        minutes: 0,
        seconds: 0,
        type: 'Cover',
        key: ['C Major'],
        bpm: 0,
        link: '',
        notes: '',
        bandId: 'band1',
    }
]